[build]
  command = "npm run build:netlify"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://upscguidetest.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200