version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add your MongoDB connection string and other environment variables here
      # - MONGODB_URI=your_mongodb_uri