[build]
  base = "Frontend"
  publish = "dist"
  command = "node patch-rollup.cjs && ROLLUP_SKIP_LOAD_NATIVE_PLUGIN=true npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  ROLLUP_SKIP_LOAD_NATIVE_PLUGIN = "true"